apiVersion: v1
kind: Service

metadata:
  name: app-service  # This is the Service's name, used for identification within the cluster.

spec:
  type: ClusterIP  # Specifies that this is a ClusterIP Service.

  selector:
    app: app-deployment  # Routes traffic to Pods with the "app" label set to "app-deployment."

  ports:
    - name: app-service-http  # The name assigned to this port, which is "app-deployment."
      protocol: TCP  # This port uses the TCP protocol.
      port: 5000  # The Service listens on port 5000.
      targetPort: 3000  # Forwards traffic to Pods' port 3000.
